name: Generate QR Code

on:
  push:
    branches:
      - main

jobs:
  qr-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install qrcode[pil]

      - name: Generate QR code
        run: |
          python -c "
import qrcode
data = 'https://github.com/tuusuario/tu-repositorio'
qr = qrcode.QRCode(version=1, error_correction=qrcode.constants.ERROR_CORRECT_L, box_size=10, border=4)
qr.add_data(data)
qr.make(fit=True)
img = qr.make_image(fill='black', back_color='white')
img.save('codigo_qr.png')
          "

      - name: Upload QR code
        uses: actions/upload-artifact@v3
        with:
          name: qr-code
          path: codigo_qr.png
